apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
#596973367895.dkr.ecr.us-east-2.amazonaws.com/onyxhawk
#  image: ghcr.io/stefanprodan/podinfo
  image: 596973367895.dkr.ecr.us-east-2.amazonaws.com/onyxhawk
  interval: 1m0s
