apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podapp
  namespace: flux-system
spec:
  providerRef: 
    name: teams
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
