apiVersion: apps/v1
kind: Deployment
metadata:
  name: winnie-pod
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.3 # {"$imagepolicy": "flux-system:podinfo"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9890
              protocol: TCP
#i-02c6fe7ba1ae75bb2 - EC2 ID
