apiVersion: apps/v1
kind: Deployment
metadata:
  name: winnie-pod
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: 596973367895.dkr.ecr.us-east-2.amazonaws.com/onyxhawk:latest # {"$imagepolicy": "flux-system:podinfo"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9890
              protocol: TCP
